---
- name: Copy .bashrc
  copy: dest=/home/vagrant/.bashrc
        src=files/bashrc
  tags: shell

- name: Copy .bash_profile
  copy: dest=/home/vagrant/.bash_profile
        src=files/bash_profile
  tags: shell

- name: Update apt
  apt: update_cache=yes
  sudo: yes
  tags: common

- name: Install dependencies
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - git
    - curl
    - build-essential
    - libssl-dev
    - fontconfig # needed for phantomjs
    - nfs-common # make virtualbox faster
  tags: common
