---
- name: update apt cache
  sudo: yes
  apt: update-cache=yes
  tags: common

- name: install system tools
  sudo: yes
  apt: pkg={{ item }} state=present
  with_items:
    # - linux-headers-generic
    - build-essential
    - libssl-dev
    # - dkms
    - git
  tags: common
